DROP DATABASE IF EXISTS `udp_data`;
CREATE DATABASE `udp_data`;
USE `udp_data`;
DROP TABLE IF EXISTS `udp`;

CREATE TABLE `udp` (
	`id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '主键；自增长ID', 
	`ip` VARCHAR(100) DEFAULT NULL COMMENT 'ip地址', 
	`requested` VARCHAR(100) DEFAULT NULL COMMENT '请求', 
	`traced` VARCHAR(100) DEFAULT NULL COMMENT '跟踪', 
	`api` VARCHAR(100) DEFAULT NULL COMMENT '应用程序', 
	`mean` VARCHAR(100) DEFAULT NULL COMMENT '连接时间', 
	`comment` VARCHAR(1000) DEFAULT NULL COMMENT '评论' ,
	PRIMARY KEY(`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 0 CHARSET = utf8 COMMENT = 'UDP接收数据';